### ISSUE TITLE
Bagaimana cara submit score?

### ISSUE THREAD

**Issue by Wikidepia** [indolem/indolem#6]
Halo, saya ingin submit score dari benchmark IndoLEM pada sentiment analysis. Cara submitnya bagaimana ya?

Terimakasih :)

**Comment by fajri91** [comment]
Halo,

Untuk saat ini submission bisa dilakukan via email ke `indolem.benchmark@gmail.com`.

Yang diperlukan adalah:
1. Nama Task.
2. Skor test set, (averaged 5-folds jika dataset menggunakan 5-folds)
3. Link ke paper (jika ada)
4. Link ke code github untuk memproduksi skor tersebut.

Kami sedang mempersiapkan form submission. Untuk saat ini bisa dilakukan dengan mengirimkan email ini.

Fajri

**Comment by Wikidepia** [comment]
Ok terimakasih mas Fajri 👍
